#include <string>
#include <iostream>

#ifdef __linux__

#define TEXT_RESET "\033[0m"

//stiles

#define TEXT_BOLD "\033[1m"
#define TEXT_UNDERLINE "\033[4m"

//colors
#define TEXT_BLACK "\033[30m"
#define TEXT_RED "\033[31m"
#define TEXT_GREEN "\033[32m"
#define TEXT_YELLOW "\033[33m"
#define TEXT_BLUE "\033[34m"
#define TEXT_MAGENTA "\033[35m"
#define TEXT_CYAN "\033[36m"
#define TEXT_WHITE "\033[37m"
#define TEXT_BRIGHT_BLACK "\033[90m"
#define TEXT_BRIGHT_RED "\033[91m"
#define TEXT_BRIGHT_GREEN "\033[92m"
#define TEXT_BRIGHT_YELLOW "\033[93m"
#define TEXT_BRIGHT_BLUE "\033[94m"
#define TEXT_BRIGHT_MAGENTA "\033[95m"
#define TEXT_BRIGHT_CYAN "\033[96m"
#define TEXT_BRIGHT_WHITE "\033[97m"

#define BG_BLACK "\033[40m"
#define BG_RED "\033[41m"
#define BG_GREEN "\33[42m"
#define BG_YELLOW "\033[43m"
#define BG_BLUE "\033[44m"
#define BG_MAGENTA "\033[45m"
#define BG_CYAN "\033[46m"
#define BG_WHITE "\033[47m"
#define BG_BRIGHT_BLACK "\033[100m"
#define BG_BRIGHT_RED "\033[101m"
#define BG_BRIGHT_GREEN "\033[102m"
#define BG_BRIGHT_YELLOW "\033[103m"
#define BG_BRIGHT_BLUE "\033[104m"
#define BG_BRIGHT_MAGENTA "\033[105m"
#define BG_BRIGHT_CYAN "\033[106m"
#define BG_BRIGHT_WHITE "\033[107m"

#define TEXT_BG_BLACK_BLACK TEXT_BLACK BG_BLACK
#define TEXT_BG_BLUE_BLACK TEXT_BLUE BG_BLACK
#define TEXT_BG_GREEN_BLACK TEXT_GREEN BG_BLACK
#define TEXT_BG_CYAN_BLACK TEXT_CYAN BG_BLACK
#define TEXT_BG_RED_BLACK TEXT_RED BG_BLACK
#define TEXT_BG_MAGENTA_BLACK TEXT_MAGENTA BG_BLACK
#define TEXT_BG_YELLOW_BLACK TEXT_YELLOW BG_BLACK
#define TEXT_BG_WHITE_BLACK TEXT_WHITE BG_BLACK
#define TEXT_BG_BRIGHT_BLACK_BLACK TEXT_BRIGHT_BLACK BG_BLACK
#define TEXT_BG_BRIGHT_BLUE_BLACK TEXT_BRIGHT_BLUE BG_BLACK
#define TEXT_BG_BRIGHT_GREEN_BLACK TEXT_BRIGHT_GREEN BG_BLACK
#define TEXT_BG_BRIGHT_CYAN_BLACK TEXT_BRIGHT_CYAN BG_BLACK
#define TEXT_BG_BRIGHT_RED_BLACK TEXT_BRIGHT_RED BG_BLACK
#define TEXT_BG_BRIGHT_MAGENTA_BLACK TEXT_BRIGHT_MAGENTA BG_BLACK
#define TEXT_BG_BRIGHT_YELLOW_BLACK TEXT_BRIGHT_YELLOW BG_BLACK
#define TEXT_BG_BRIGHT_WHITE_BLACK TEXT_BRIGHT_WHITE BG_BLACK

#define TEXT_BG_BLACK_BLUE TEXT_BLACK BG_BLUE
#define TEXT_BG_BLUE_BLUE TEXT_BLUE BG_BLUE
#define TEXT_BG_GREEN_BLUE TEXT_GREEN BG_BLUE
#define TEXT_BG_CYAN_BLUE TEXT_CYAN BG_BLUE
#define TEXT_BG_RED_BLUE TEXT_RED BG_BLUE
#define TEXT_BG_MAGENTA_BLUE TEXT_MAGENTA BG_BLUE
#define TEXT_BG_YELLOW_BLUE TEXT_YELLOW BG_BLUE
#define TEXT_BG_WHITE_BLUE TEXT_WHITE BG_BLUE
#define TEXT_BG_BRIGHT_BLACK_BLUE TEXT_BRIGHT_BLACK BG_BLUE
#define TEXT_BG_BRIGHT_BLUE_BLUE TEXT_BRIGHT_BLUE BG_BLUE
#define TEXT_BG_BRIGHT_GREEN_BLUE TEXT_BRIGHT_GREEN BG_BLUE
#define TEXT_BG_BRIGHT_CYAN_BLUE TEXT_BRIGHT_CYAN BG_BLUE
#define TEXT_BG_BRIGHT_RED_BLUE TEXT_BRIGHT_RED BG_BLUE
#define TEXT_BG_BRIGHT_MAGENTA_BLUE TEXT_BRIGHT_MAGENTA BG_BLUE
#define TEXT_BG_BRIGHT_YELLOW_BLUE TEXT_BRIGHT_YELLOW BG_BLUE
#define TEXT_BG_BRIGHT_WHITE_BLUE TEXT_BRIGHT_WHITE BG_BLUE

#define TEXT_BG_BLACK_GREEN TEXT_BLACK BG_GREEN
#define TEXT_BG_BLUE_GREEN TEXT_BLUE BG_GREEN
#define TEXT_BG_GREEN_GREEN TEXT_GREEN BG_GREEN
#define TEXT_BG_CYAN_GREEN TEXT_CYAN BG_GREEN
#define TEXT_BG_RED_GREEN TEXT_RED BG_GREEN
#define TEXT_BG_MAGENTA_GREEN TEXT_MAGENTA BG_GREEN
#define TEXT_BG_YELLOW_GREEN TEXT_YELLOW BG_GREEN
#define TEXT_BG_WHITE_GREEN TEXT_WHITE BG_GREEN
#define TEXT_BG_BRIGHT_BLACK_GREEN TEXT_BRIGHT_BLACK BG_GREEN
#define TEXT_BG_BRIGHT_BLUE_GREEN TEXT_BRIGHT_BLUE BG_GREEN
#define TEXT_BG_BRIGHT_GREEN_GREEN TEXT_BRIGHT_GREEN BG_GREEN
#define TEXT_BG_BRIGHT_CYAN_GREEN TEXT_BRIGHT_CYAN BG_GREEN
#define TEXT_BG_BRIGHT_RED_GREEN TEXT_BRIGHT_RED BG_GREEN
#define TEXT_BG_BRIGHT_MAGENTA_GREEN TEXT_BRIGHT_MAGENTA BG_GREEN
#define TEXT_BG_BRIGHT_YELLOW_GREEN TEXT_BRIGHT_YELLOW BG_GREEN
#define TEXT_BG_BRIGHT_WHITE_GREEN TEXT_BRIGHT_WHITE BG_GREEN

#define TEXT_BG_BLACK_CYAN TEXT_BLACK BG_CYAN
#define TEXT_BG_BLUE_CYAN TEXT_BLUE BG_CYAN
#define TEXT_BG_GREEN_CYAN TEXT_GREEN BG_CYAN
#define TEXT_BG_CYAN_CYAN TEXT_CYAN BG_CYAN
#define TEXT_BG_RED_CYAN TEXT_RED BG_CYAN
#define TEXT_BG_MAGENTA_CYAN TEXT_MAGENTA BG_CYAN
#define TEXT_BG_YELLOW_CYAN TEXT_YELLOW BG_CYAN
#define TEXT_BG_WHITE_CYAN TEXT_WHITE BG_CYAN
#define TEXT_BG_BRIGHT_BLACK_CYAN TEXT_BRIGHT_BLACK BG_CYAN
#define TEXT_BG_BRIGHT_BLUE_CYAN TEXT_BRIGHT_BLUE BG_CYAN
#define TEXT_BG_BRIGHT_GREEN_CYAN TEXT_BRIGHT_GREEN BG_CYAN
#define TEXT_BG_BRIGHT_CYAN_CYAN TEXT_BRIGHT_CYAN BG_CYAN
#define TEXT_BG_BRIGHT_RED_CYAN TEXT_BRIGHT_RED BG_CYAN
#define TEXT_BG_BRIGHT_MAGENTA_CYAN TEXT_BRIGHT_MAGENTA BG_CYAN
#define TEXT_BG_BRIGHT_YELLOW_CYAN TEXT_BRIGHT_YELLOW BG_CYAN
#define TEXT_BG_BRIGHT_WHITE_CYAN TEXT_BRIGHT_WHITE BG_CYAN

#define TEXT_BG_BLACK_RED TEXT_BLACK BG_RED
#define TEXT_BG_BLUE_RED TEXT_BLUE BG_RED
#define TEXT_BG_GREEN_RED TEXT_GREEN BG_RED
#define TEXT_BG_CYAN_RED TEXT_CYAN BG_RED
#define TEXT_BG_RED_RED TEXT_RED BG_RED
#define TEXT_BG_MAGENTA_RED TEXT_MAGENTA BG_RED
#define TEXT_BG_YELLOW_RED TEXT_YELLOW BG_RED
#define TEXT_BG_WHITE_RED TEXT_WHITE BG_RED
#define TEXT_BG_BRIGHT_BLACK_RED TEXT_BRIGHT_BLACK BG_RED
#define TEXT_BG_BRIGHT_BLUE_RED TEXT_BRIGHT_BLUE BG_RED
#define TEXT_BG_BRIGHT_GREEN_RED TEXT_BRIGHT_GREEN BG_RED
#define TEXT_BG_BRIGHT_CYAN_RED TEXT_BRIGHT_CYAN BG_RED
#define TEXT_BG_BRIGHT_RED_RED TEXT_BRIGHT_RED BG_RED
#define TEXT_BG_BRIGHT_MAGENTA_RED TEXT_BRIGHT_MAGENTA BG_RED
#define TEXT_BG_BRIGHT_YELLOW_RED TEXT_BRIGHT_YELLOW BG_RED
#define TEXT_BG_BRIGHT_WHITE_RED TEXT_BRIGHT_WHITE BG_RED

#define TEXT_BG_BLACK_MAGENTA TEXT_BLACK BG_MAGENTA
#define TEXT_BG_BLUE_MAGENTA TEXT_BLUE BG_MAGENTA
#define TEXT_BG_GREEN_MAGENTA TEXT_GREEN BG_MAGENTA
#define TEXT_BG_CYAN_MAGENTA TEXT_CYAN BG_MAGENTA
#define TEXT_BG_RED_MAGENTA TEXT_RED BG_MAGENTA
#define TEXT_BG_MAGENTA_MAGENTA TEXT_MAGENTA BG_MAGENTA
#define TEXT_BG_YELLOW_MAGENTA TEXT_YELLOW BG_MAGENTA
#define TEXT_BG_WHITE_MAGENTA TEXT_WHITE BG_MAGENTA
#define TEXT_BG_BRIGHT_BLACK_MAGENTA TEXT_BRIGHT_BLACK BG_MAGENTA
#define TEXT_BG_BRIGHT_BLUE_MAGENTA TEXT_BRIGHT_BLUE BG_MAGENTA
#define TEXT_BG_BRIGHT_GREEN_MAGENTA TEXT_BRIGHT_GREEN BG_MAGENTA
#define TEXT_BG_BRIGHT_CYAN_MAGENTA TEXT_BRIGHT_CYAN BG_MAGENTA
#define TEXT_BG_BRIGHT_RED_MAGENTA TEXT_BRIGHT_RED BG_MAGENTA
#define TEXT_BG_BRIGHT_MAGENTA_MAGENTA TEXT_BRIGHT_MAGENTA BG_MAGENTA
#define TEXT_BG_BRIGHT_YELLOW_MAGENTA TEXT_BRIGHT_YELLOW BG_MAGENTA
#define TEXT_BG_BRIGHT_WHITE_MAGENTA TEXT_BRIGHT_WHITE BG_MAGENTA

#define TEXT_BG_BLACK_YELLOW TEXT_BLACK BG_YELLOW
#define TEXT_BG_BLUE_YELLOW TEXT_BLUE BG_YELLOW
#define TEXT_BG_GREEN_YELLOW TEXT_GREEN BG_YELLOW
#define TEXT_BG_CYAN_YELLOW TEXT_CYAN BG_YELLOW
#define TEXT_BG_RED_YELLOW TEXT_RED BG_YELLOW
#define TEXT_BG_MAGENTA_YELLOW TEXT_MAGENTA BG_YELLOW
#define TEXT_BG_YELLOW_YELLOW TEXT_YELLOW BG_YELLOW
#define TEXT_BG_WHITE_YELLOW TEXT_WHITE BG_YELLOW
#define TEXT_BG_BRIGHT_BLACK_YELLOW TEXT_BRIGHT_BLACK BG_YELLOW
#define TEXT_BG_BRIGHT_BLUE_YELLOW TEXT_BRIGHT_BLUE BG_YELLOW
#define TEXT_BG_BRIGHT_GREEN_YELLOW TEXT_BRIGHT_GREEN BG_YELLOW
#define TEXT_BG_BRIGHT_CYAN_YELLOW TEXT_BRIGHT_CYAN BG_YELLOW
#define TEXT_BG_BRIGHT_RED_YELLOW TEXT_BRIGHT_RED BG_YELLOW
#define TEXT_BG_BRIGHT_MAGENTA_YELLOW TEXT_BRIGHT_MAGENTA BG_YELLOW
#define TEXT_BG_BRIGHT_YELLOW_YELLOW TEXT_BRIGHT_YELLOW BG_YELLOW
#define TEXT_BG_BRIGHT_WHITE_YELLOW TEXT_BRIGHT_WHITE BG_YELLOW

#define TEXT_BG_BLACK_WHITE TEXT_BLACK BG_WHITE
#define TEXT_BG_BLUE_WHITE TEXT_BLUE BG_WHITE
#define TEXT_BG_GREEN_WHITE TEXT_GREEN BG_WHITE
#define TEXT_BG_CYAN_WHITE TEXT_CYAN BG_WHITE
#define TEXT_BG_RED_WHITE TEXT_RED BG_WHITE
#define TEXT_BG_MAGENTA_WHITE TEXT_MAGENTA BG_WHITE
#define TEXT_BG_YELLOW_WHITE TEXT_YELLOW BG_WHITE
#define TEXT_BG_WHITE_WHITE TEXT_WHITE BG_WHITE
#define TEXT_BG_BRIGHT_BLACK_WHITE TEXT_BRIGHT_BLACK BG_WHITE
#define TEXT_BG_BRIGHT_BLUE_WHITE TEXT_BRIGHT_BLUE BG_WHITE
#define TEXT_BG_BRIGHT_GREEN_WHITE TEXT_BRIGHT_GREEN BG_WHITE
#define TEXT_BG_BRIGHT_CYAN_WHITE TEXT_BRIGHT_CYAN BG_WHITE
#define TEXT_BG_BRIGHT_RED_WHITE TEXT_BRIGHT_RED BG_WHITE
#define TEXT_BG_BRIGHT_MAGENTA_WHITE TEXT_BRIGHT_MAGENTA BG_WHITE
#define TEXT_BG_BRIGHT_YELLOW_WHITE TEXT_BRIGHT_YELLOW BG_WHITE
#define TEXT_BG_BRIGHT_WHITE_WHITE TEXT_BRIGHT_WHITE BG_WHITE

#define TEXT_BG_BLACK_BRIGHT_BLACK TEXT_BLACK BG_BRIGHT_BLACK
#define TEXT_BG_BLUE_BRIGHT_BLACK TEXT_BLUE BG_BRIGHT_BLACK
#define TEXT_BG_GREEN_BRIGHT_BLACK TEXT_GREEN BG_BRIGHT_BLACK
#define TEXT_BG_CYAN_BRIGHT_BLACK TEXT_CYAN BG_BRIGHT_BLACK
#define TEXT_BG_RED_BRIGHT_BLACK TEXT_RED BG_BRIGHT_BLACK
#define TEXT_BG_MAGENTA_BRIGHT_BLACK TEXT_MAGENTA BG_BRIGHT_BLACK
#define TEXT_BG_YELLOW_BRIGHT_BLACK TEXT_YELLOW BG_BRIGHT_BLACK
#define TEXT_BG_WHITE_BRIGHT_BLACK TEXT_WHITE BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_BLACK TEXT_BRIGHT_BLACK BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_BLACK TEXT_BRIGHT_BLUE BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_BLACK TEXT_BRIGHT_GREEN BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_BLACK TEXT_BRIGHT_CYAN BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_RED_BRIGHT_BLACK TEXT_BRIGHT_RED BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_BLACK TEXT_BRIGHT_MAGENTA BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_BLACK TEXT_BRIGHT_YELLOW BG_BRIGHT_BLACK
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_BLACK TEXT_BRIGHT_WHITE BG_BRIGHT_BLACK

#define TEXT_BG_BLACK_BRIGHT_BLUE TEXT_BLACK BG_BRIGHT_BLUE
#define TEXT_BG_BLUE_BRIGHT_BLUE TEXT_BLUE BG_BRIGHT_BLUE
#define TEXT_BG_GREEN_BRIGHT_BLUE TEXT_GREEN BG_BRIGHT_BLUE
#define TEXT_BG_CYAN_BRIGHT_BLUE TEXT_CYAN BG_BRIGHT_BLUE
#define TEXT_BG_RED_BRIGHT_BLUE TEXT_RED BG_BRIGHT_BLUE
#define TEXT_BG_MAGENTA_BRIGHT_BLUE TEXT_MAGENTA BG_BRIGHT_BLUE
#define TEXT_BG_YELLOW_BRIGHT_BLUE TEXT_YELLOW BG_BRIGHT_BLUE
#define TEXT_BG_WHITE_BRIGHT_BLUE TEXT_WHITE BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_BLUE TEXT_BRIGHT_BLACK BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_BLUE TEXT_BRIGHT_BLUE BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_BLUE TEXT_BRIGHT_GREEN BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_BLUE TEXT_BRIGHT_CYAN BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_RED_BRIGHT_BLUE TEXT_BRIGHT_RED BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_BLUE TEXT_BRIGHT_MAGENTA BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_BLUE TEXT_BRIGHT_YELLOW BG_BRIGHT_BLUE
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_BLUE TEXT_BRIGHT_WHITE BG_BRIGHT_BLUE

#define TEXT_BG_BLACK_BRIGHT_GREEN TEXT_BLACK BG_BRIGHT_GREEN
#define TEXT_BG_BLUE_BRIGHT_GREEN TEXT_BLUE BG_BRIGHT_GREEN
#define TEXT_BG_GREEN_BRIGHT_GREEN TEXT_GREEN BG_BRIGHT_GREEN
#define TEXT_BG_CYAN_BRIGHT_GREEN TEXT_CYAN BG_BRIGHT_GREEN
#define TEXT_BG_RED_BRIGHT_GREEN TEXT_RED BG_BRIGHT_GREEN
#define TEXT_BG_MAGENTA_BRIGHT_GREEN TEXT_MAGENTA BG_BRIGHT_GREEN
#define TEXT_BG_YELLOW_BRIGHT_GREEN TEXT_YELLOW BG_BRIGHT_GREEN
#define TEXT_BG_WHITE_BRIGHT_GREEN TEXT_WHITE BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_GREEN TEXT_BRIGHT_BLACK BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_GREEN TEXT_BRIGHT_BLUE BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_GREEN TEXT_BRIGHT_GREEN BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_GREEN TEXT_BRIGHT_CYAN BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_RED_BRIGHT_GREEN TEXT_BRIGHT_RED BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_GREEN TEXT_BRIGHT_MAGENTA BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_GREEN TEXT_BRIGHT_YELLOW BG_BRIGHT_GREEN
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_GREEN TEXT_BRIGHT_WHITE BG_BRIGHT_GREEN

#define TEXT_BG_BLACK_BRIGHT_CYAN TEXT_BLACK BG_BRIGHT_CYAN
#define TEXT_BG_BLUE_BRIGHT_CYAN TEXT_BLUE BG_BRIGHT_CYAN
#define TEXT_BG_GREEN_BRIGHT_CYAN TEXT_GREEN BG_BRIGHT_CYAN
#define TEXT_BG_CYAN_BRIGHT_CYAN TEXT_CYAN BG_BRIGHT_CYAN
#define TEXT_BG_RED_BRIGHT_CYAN TEXT_RED BG_BRIGHT_CYAN
#define TEXT_BG_MAGENTA_BRIGHT_CYAN TEXT_MAGENTA BG_BRIGHT_CYAN
#define TEXT_BG_YELLOW_BRIGHT_CYAN TEXT_YELLOW BG_BRIGHT_CYAN
#define TEXT_BG_WHITE_BRIGHT_CYAN TEXT_WHITE BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_CYAN TEXT_BRIGHT_BLACK BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_CYAN TEXT_BRIGHT_BLUE BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_CYAN TEXT_BRIGHT_GREEN BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_CYAN TEXT_BRIGHT_CYAN BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_RED_BRIGHT_CYAN TEXT_BRIGHT_RED BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_CYAN TEXT_BRIGHT_MAGENTA BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_CYAN TEXT_BRIGHT_YELLOW BG_BRIGHT_CYAN
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_CYAN TEXT_BRIGHT_WHITE BG_BRIGHT_CYAN

#define TEXT_BG_BLACK_BRIGHT_RED TEXT_BLACK BG_BRIGHT_RED
#define TEXT_BG_BLUE_BRIGHT_RED TEXT_BLUE BG_BRIGHT_RED
#define TEXT_BG_GREEN_BRIGHT_RED TEXT_GREEN BG_BRIGHT_RED
#define TEXT_BG_CYAN_BRIGHT_RED TEXT_CYAN BG_BRIGHT_RED
#define TEXT_BG_RED_BRIGHT_RED TEXT_RED BG_BRIGHT_RED
#define TEXT_BG_MAGENTA_BRIGHT_RED TEXT_MAGENTA BG_BRIGHT_RED
#define TEXT_BG_YELLOW_BRIGHT_RED TEXT_YELLOW BG_BRIGHT_RED
#define TEXT_BG_WHITE_BRIGHT_RED TEXT_WHITE BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_RED TEXT_BRIGHT_BLACK BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_RED TEXT_BRIGHT_BLUE BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_RED TEXT_BRIGHT_GREEN BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_RED TEXT_BRIGHT_CYAN BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_RED_BRIGHT_RED TEXT_BRIGHT_RED BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_RED TEXT_BRIGHT_MAGENTA BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_RED TEXT_BRIGHT_YELLOW BG_BRIGHT_RED
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_RED TEXT_BRIGHT_WHITE BG_BRIGHT_RED

#define TEXT_BG_BLACK_BRIGHT_MAGENTA TEXT_BLACK BG_BRIGHT_MAGENTA
#define TEXT_BG_BLUE_BRIGHT_MAGENTA TEXT_BLUE BG_BRIGHT_MAGENTA
#define TEXT_BG_GREEN_BRIGHT_MAGENTA TEXT_GREEN BG_BRIGHT_MAGENTA
#define TEXT_BG_CYAN_BRIGHT_MAGENTA TEXT_CYAN BG_BRIGHT_MAGENTA
#define TEXT_BG_RED_BRIGHT_MAGENTA TEXT_RED BG_BRIGHT_MAGENTA
#define TEXT_BG_MAGENTA_BRIGHT_MAGENTA TEXT_MAGENTA BG_BRIGHT_MAGENTA
#define TEXT_BG_YELLOW_BRIGHT_MAGENTA TEXT_YELLOW BG_BRIGHT_MAGENTA
#define TEXT_BG_WHITE_BRIGHT_MAGENTA TEXT_WHITE BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_MAGENTA TEXT_BRIGHT_BLACK BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_MAGENTA TEXT_BRIGHT_BLUE BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_MAGENTA TEXT_BRIGHT_GREEN BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_MAGENTA TEXT_BRIGHT_CYAN BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_RED_BRIGHT_MAGENTA TEXT_BRIGHT_RED BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_MAGENTA TEXT_BRIGHT_MAGENTA BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_MAGENTA TEXT_BRIGHT_YELLOW BG_BRIGHT_MAGENTA
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_MAGENTA TEXT_BRIGHT_WHITE BG_BRIGHT_MAGENTA

#define TEXT_BG_BLACK_BRIGHT_YELLOW TEXT_BLACK BG_BRIGHT_YELLOW
#define TEXT_BG_BLUE_BRIGHT_YELLOW TEXT_BLUE BG_BRIGHT_YELLOW
#define TEXT_BG_GREEN_BRIGHT_YELLOW TEXT_GREEN BG_BRIGHT_YELLOW
#define TEXT_BG_CYAN_BRIGHT_YELLOW TEXT_CYAN BG_BRIGHT_YELLOW
#define TEXT_BG_RED_BRIGHT_YELLOW TEXT_RED BG_BRIGHT_YELLOW
#define TEXT_BG_MAGENTA_BRIGHT_YELLOW TEXT_MAGENTA BG_BRIGHT_YELLOW
#define TEXT_BG_YELLOW_BRIGHT_YELLOW TEXT_YELLOW BG_BRIGHT_YELLOW
#define TEXT_BG_WHITE_BRIGHT_YELLOW TEXT_WHITE BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_YELLOW TEXT_BRIGHT_BLACK BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_YELLOW TEXT_BRIGHT_BLUE BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_YELLOW TEXT_BRIGHT_GREEN BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_YELLOW TEXT_BRIGHT_CYAN BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_RED_BRIGHT_YELLOW TEXT_BRIGHT_RED BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_YELLOW TEXT_BRIGHT_MAGENTA BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_YELLOW TEXT_BRIGHT_YELLOW BG_BRIGHT_YELLOW
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_YELLOW TEXT_BRIGHT_WHITE BG_BRIGHT_YELLOW

#define TEXT_BG_BLACK_BRIGHT_WHITE TEXT_BLACK BG_BRIGHT_WHITE
#define TEXT_BG_BLUE_BRIGHT_WHITE TEXT_BLUE BG_BRIGHT_WHITE
#define TEXT_BG_GREEN_BRIGHT_WHITE TEXT_GREEN BG_BRIGHT_WHITE
#define TEXT_BG_CYAN_BRIGHT_WHITE TEXT_CYAN BG_BRIGHT_WHITE
#define TEXT_BG_RED_BRIGHT_WHITE TEXT_RED BG_BRIGHT_WHITE
#define TEXT_BG_MAGENTA_BRIGHT_WHITE TEXT_MAGENTA BG_BRIGHT_WHITE
#define TEXT_BG_YELLOW_BRIGHT_WHITE TEXT_YELLOW BG_BRIGHT_WHITE
#define TEXT_BG_WHITE_BRIGHT_WHITE TEXT_WHITE BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_WHITE TEXT_BRIGHT_BLACK BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_WHITE TEXT_BRIGHT_BLUE BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_WHITE TEXT_BRIGHT_GREEN BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_WHITE TEXT_BRIGHT_CYAN BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_RED_BRIGHT_WHITE TEXT_BRIGHT_RED BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_WHITE TEXT_BRIGHT_MAGENTA BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_WHITE TEXT_BRIGHT_YELLOW BG_BRIGHT_WHITE
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_WHITE TEXT_BRIGHT_WHITE BG_BRIGHT_WHITE

std::string TEXT_RGB( int R = 0, int G = 0, int B = 0 )
{
	return "\033[38;2;" + std::to_string(R) + ";" + std::to_string(G) + ";" + std::to_string(B) + "m";
}

std::string BG_RGB( int R = 0, int G = 0, int B = 0 )
{
	return "\033[48;2;" + std::to_string(R) + ";" + std::to_string(G) + ";" + std::to_string(B) + "m";
}

#endif

#ifdef __WIN32

#include <windows.h>
HANDLE TEXT_BG_CONSOLE_HANDLE = GetStdHandle(STD_OUTPUT_HANDLE);


const char *TEXT_BG_SET( int color )
{
	SetConsoleTextAttribute(TEXT_BG_CONSOLE_HANDLE, color);

	return "";
}



//stiles

#define TEXT_BOLD ""
#define TEXT_UNDERLINE ""

//colors
#define TEXT_BLACK TEXT_BG_SET(0)
#define TEXT_BLUE TEXT_BG_SET(1)
#define TEXT_GREEN TEXT_BG_SET(2)
#define TEXT_CYAN TEXT_BG_SET(3)
#define TEXT_RED TEXT_BG_SET(4)
#define TEXT_MAGENTA TEXT_BG_SET(5)
#define TEXT_YELLOW TEXT_BG_SET(6)
#define TEXT_WHITE TEXT_BG_SET(7)
#define TEXT_BRIGHT_BLACK TEXT_BG_SET(8)
#define TEXT_BRIGHT_BLUE TEXT_BG_SET(9)
#define TEXT_BRIGHT_GREEN TEXT_BG_SET(10)
#define TEXT_BRIGHT_CYAN TEXT_BG_SET(11)
#define TEXT_BRIGHT_RED TEXT_BG_SET(12)
#define TEXT_BRIGHT_MAGENTA TEXT_BG_SET(13)
#define TEXT_BRIGHT_YELLOW TEXT_BG_SET(14)
#define TEXT_BRIGHT_WHITE TEXT_BG_SET(15)

#define BG_BLACK ""
#define BG_BLUE ""
#define BG_GREEN ""
#define BG_CYAN ""
#define BG_RED ""
#define BG_MAGENTA ""
#define BG_YELLOW ""
#define BG_WHITE ""
#define BG_BRIGHT_BLACK ""
#define BG_BRIGHT_BLUE ""
#define BG_BRIGHT_GREEN ""
#define BG_BRIGHT_CYAN ""
#define BG_BRIGHT_RED ""
#define BG_BRIGHT_MAGENTA ""
#define BG_BRIGHT_YELLOW ""
#define BG_BRIGHT_WHITE ""

#define TEXT_BG_BLACK_BLACK TEXT_BG_SET(0)
#define TEXT_BG_BLUE_BLACK TEXT_BG_SET(1)
#define TEXT_BG_GREEN_BLACK TEXT_BG_SET(2)
#define TEXT_BG_CYAN_BLACK TEXT_BG_SET(3)
#define TEXT_BG_RED_BLACK TEXT_BG_SET(4)
#define TEXT_BG_MAGENTA_BLACK TEXT_BG_SET(5)
#define TEXT_BG_YELLOW_BLACK TEXT_BG_SET(6)
#define TEXT_BG_WHITE_BLACK TEXT_BG_SET(7)
#define TEXT_BG_BRIGHT_BLACK_BLACK TEXT_BG_SET(8)
#define TEXT_BG_BRIGHT_BLUE_BLACK TEXT_BG_SET(9)
#define TEXT_BG_BRIGHT_GREEN_BLACK TEXT_BG_SET(10)
#define TEXT_BG_BRIGHT_CYAN_BLACK TEXT_BG_SET(11)
#define TEXT_BG_BRIGHT_RED_BLACK TEXT_BG_SET(12)
#define TEXT_BG_BRIGHT_MAGENTA_BLACK TEXT_BG_SET(13)
#define TEXT_BG_BRIGHT_YELLOW_BLACK TEXT_BG_SET(14)
#define TEXT_BG_BRIGHT_WHITE_BLACK TEXT_BG_SET(15)

#define TEXT_BG_BLACK_BLUE TEXT_BG_SET(16)
#define TEXT_BG_BLUE_BLUE TEXT_BG_SET(17)
#define TEXT_BG_GREEN_BLUE TEXT_BG_SET(18)
#define TEXT_BG_CYAN_BLUE TEXT_BG_SET(19)
#define TEXT_BG_RED_BLUE TEXT_BG_SET(20)
#define TEXT_BG_MAGENTA_BLUE TEXT_BG_SET(21)
#define TEXT_BG_YELLOW_BLUE TEXT_BG_SET(22)
#define TEXT_BG_WHITE_BLUE TEXT_BG_SET(23)
#define TEXT_BG_BRIGHT_BLACK_BLUE TEXT_BG_SET(24)
#define TEXT_BG_BRIGHT_BLUE_BLUE TEXT_BG_SET(25)
#define TEXT_BG_BRIGHT_GREEN_BLUE TEXT_BG_SET(26)
#define TEXT_BG_BRIGHT_CYAN_BLUE TEXT_BG_SET(27)
#define TEXT_BG_BRIGHT_RED_BLUE TEXT_BG_SET(28)
#define TEXT_BG_BRIGHT_MAGENTA_BLUE TEXT_BG_SET(29)
#define TEXT_BG_BRIGHT_YELLOW_BLUE TEXT_BG_SET(30)
#define TEXT_BG_BRIGHT_WHITE_BLUE TEXT_BG_SET(31)

#define TEXT_BG_BLACK_GREEN TEXT_BG_SET(32)
#define TEXT_BG_BLUE_GREEN TEXT_BG_SET(33)
#define TEXT_BG_GREEN_GREEN TEXT_BG_SET(34)
#define TEXT_BG_CYAN_GREEN TEXT_BG_SET(35)
#define TEXT_BG_RED_GREEN TEXT_BG_SET(36)
#define TEXT_BG_MAGENTA_GREEN TEXT_BG_SET(37)
#define TEXT_BG_YELLOW_GREEN TEXT_BG_SET(38)
#define TEXT_BG_WHITE_GREEN TEXT_BG_SET(39)
#define TEXT_BG_BRIGHT_BLACK_GREEN TEXT_BG_SET(40)
#define TEXT_BG_BRIGHT_BLUE_GREEN TEXT_BG_SET(41)
#define TEXT_BG_BRIGHT_GREEN_GREEN TEXT_BG_SET(42)
#define TEXT_BG_BRIGHT_CYAN_GREEN TEXT_BG_SET(43)
#define TEXT_BG_BRIGHT_RED_GREEN TEXT_BG_SET(44)
#define TEXT_BG_BRIGHT_MAGENTA_GREEN TEXT_BG_SET(45)
#define TEXT_BG_BRIGHT_YELLOW_GREEN TEXT_BG_SET(46)
#define TEXT_BG_BRIGHT_WHITE_GREEN TEXT_BG_SET(47)

#define TEXT_BG_BLACK_CYAN TEXT_BG_SET(48)
#define TEXT_BG_BLUE_CYAN TEXT_BG_SET(49)
#define TEXT_BG_GREEN_CYAN TEXT_BG_SET(50)
#define TEXT_BG_CYAN_CYAN TEXT_BG_SET(51)
#define TEXT_BG_RED_CYAN TEXT_BG_SET(52)
#define TEXT_BG_MAGENTA_CYAN TEXT_BG_SET(53)
#define TEXT_BG_YELLOW_CYAN TEXT_BG_SET(54)
#define TEXT_BG_WHITE_CYAN TEXT_BG_SET(55)
#define TEXT_BG_BRIGHT_BLACK_CYAN TEXT_BG_SET(56)
#define TEXT_BG_BRIGHT_BLUE_CYAN TEXT_BG_SET(57)
#define TEXT_BG_BRIGHT_GREEN_CYAN TEXT_BG_SET(58)
#define TEXT_BG_BRIGHT_CYAN_CYAN TEXT_BG_SET(59)
#define TEXT_BG_BRIGHT_RED_CYAN TEXT_BG_SET(60)
#define TEXT_BG_BRIGHT_MAGENTA_CYAN TEXT_BG_SET(61)
#define TEXT_BG_BRIGHT_YELLOW_CYAN TEXT_BG_SET(62)
#define TEXT_BG_BRIGHT_WHITE_CYAN TEXT_BG_SET(63)

#define TEXT_BG_BLACK_RED TEXT_BG_SET(64)
#define TEXT_BG_BLUE_RED TEXT_BG_SET(65)
#define TEXT_BG_GREEN_RED TEXT_BG_SET(66)
#define TEXT_BG_CYAN_RED TEXT_BG_SET(67)
#define TEXT_BG_RED_RED TEXT_BG_SET(68)
#define TEXT_BG_MAGENTA_RED TEXT_BG_SET(69)
#define TEXT_BG_YELLOW_RED TEXT_BG_SET(70)
#define TEXT_BG_WHITE_RED TEXT_BG_SET(71)
#define TEXT_BG_BRIGHT_BLACK_RED TEXT_BG_SET(72)
#define TEXT_BG_BRIGHT_BLUE_RED TEXT_BG_SET(73)
#define TEXT_BG_BRIGHT_GREEN_RED TEXT_BG_SET(74)
#define TEXT_BG_BRIGHT_CYAN_RED TEXT_BG_SET(75)
#define TEXT_BG_BRIGHT_RED_RED TEXT_BG_SET(76)
#define TEXT_BG_BRIGHT_MAGENTA_RED TEXT_BG_SET(77)
#define TEXT_BG_BRIGHT_YELLOW_RED TEXT_BG_SET(78)
#define TEXT_BG_BRIGHT_WHITE_RED TEXT_BG_SET(79)

#define TEXT_BG_BLACK_MAGENTA TEXT_BG_SET(80)
#define TEXT_BG_BLUE_MAGENTA TEXT_BG_SET(81)
#define TEXT_BG_GREEN_MAGENTA TEXT_BG_SET(82)
#define TEXT_BG_CYAN_MAGENTA TEXT_BG_SET(83)
#define TEXT_BG_RED_MAGENTA TEXT_BG_SET(84)
#define TEXT_BG_MAGENTA_MAGENTA TEXT_BG_SET(85)
#define TEXT_BG_YELLOW_MAGENTA TEXT_BG_SET(86)
#define TEXT_BG_WHITE_MAGENTA TEXT_BG_SET(87)
#define TEXT_BG_BRIGHT_BLACK_MAGENTA TEXT_BG_SET(88)
#define TEXT_BG_BRIGHT_BLUE_MAGENTA TEXT_BG_SET(89)
#define TEXT_BG_BRIGHT_GREEN_MAGENTA TEXT_BG_SET(90)
#define TEXT_BG_BRIGHT_CYAN_MAGENTA TEXT_BG_SET(91)
#define TEXT_BG_BRIGHT_RED_MAGENTA TEXT_BG_SET(92)
#define TEXT_BG_BRIGHT_MAGENTA_MAGENTA TEXT_BG_SET(93)
#define TEXT_BG_BRIGHT_YELLOW_MAGENTA TEXT_BG_SET(94)
#define TEXT_BG_BRIGHT_WHITE_MAGENTA TEXT_BG_SET(95)

#define TEXT_BG_BLACK_YELLOW TEXT_BG_SET(96)
#define TEXT_BG_BLUE_YELLOW TEXT_BG_SET(97)
#define TEXT_BG_GREEN_YELLOW TEXT_BG_SET(98)
#define TEXT_BG_CYAN_YELLOW TEXT_BG_SET(99)
#define TEXT_BG_RED_YELLOW TEXT_BG_SET(100)
#define TEXT_BG_MAGENTA_YELLOW TEXT_BG_SET(101)
#define TEXT_BG_YELLOW_YELLOW TEXT_BG_SET(102)
#define TEXT_BG_WHITE_YELLOW TEXT_BG_SET(103)
#define TEXT_BG_BRIGHT_BLACK_YELLOW TEXT_BG_SET(104)
#define TEXT_BG_BRIGHT_BLUE_YELLOW TEXT_BG_SET(105)
#define TEXT_BG_BRIGHT_GREEN_YELLOW TEXT_BG_SET(106)
#define TEXT_BG_BRIGHT_CYAN_YELLOW TEXT_BG_SET(107)
#define TEXT_BG_BRIGHT_RED_YELLOW TEXT_BG_SET(108)
#define TEXT_BG_BRIGHT_MAGENTA_YELLOW TEXT_BG_SET(109)
#define TEXT_BG_BRIGHT_YELLOW_YELLOW TEXT_BG_SET(110)
#define TEXT_BG_BRIGHT_WHITE_YELLOW TEXT_BG_SET(111)

#define TEXT_BG_BLACK_WHITE TEXT_BG_SET(112)
#define TEXT_BG_BLUE_WHITE TEXT_BG_SET(113)
#define TEXT_BG_GREEN_WHITE TEXT_BG_SET(114)
#define TEXT_BG_CYAN_WHITE TEXT_BG_SET(115)
#define TEXT_BG_RED_WHITE TEXT_BG_SET(116)
#define TEXT_BG_MAGENTA_WHITE TEXT_BG_SET(117)
#define TEXT_BG_YELLOW_WHITE TEXT_BG_SET(118)
#define TEXT_BG_WHITE_WHITE TEXT_BG_SET(119)
#define TEXT_BG_BRIGHT_BLACK_WHITE TEXT_BG_SET(120)
#define TEXT_BG_BRIGHT_BLUE_WHITE TEXT_BG_SET(121)
#define TEXT_BG_BRIGHT_GREEN_WHITE TEXT_BG_SET(122)
#define TEXT_BG_BRIGHT_CYAN_WHITE TEXT_BG_SET(123)
#define TEXT_BG_BRIGHT_RED_WHITE TEXT_BG_SET(124)
#define TEXT_BG_BRIGHT_MAGENTA_WHITE TEXT_BG_SET(125)
#define TEXT_BG_BRIGHT_YELLOW_WHITE TEXT_BG_SET(126)
#define TEXT_BG_BRIGHT_WHITE_WHITE TEXT_BG_SET(127)

#define TEXT_BG_BLACK_BRIGHT_BLACK TEXT_BG_SET(128)
#define TEXT_BG_BLUE_BRIGHT_BLACK TEXT_BG_SET(129)
#define TEXT_BG_GREEN_BRIGHT_BLACK TEXT_BG_SET(130)
#define TEXT_BG_CYAN_BRIGHT_BLACK TEXT_BG_SET(131)
#define TEXT_BG_RED_BRIGHT_BLACK TEXT_BG_SET(132)
#define TEXT_BG_MAGENTA_BRIGHT_BLACK TEXT_BG_SET(133)
#define TEXT_BG_YELLOW_BRIGHT_BLACK TEXT_BG_SET(134)
#define TEXT_BG_WHITE_BRIGHT_BLACK TEXT_BG_SET(135)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_BLACK TEXT_BG_SET(136)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_BLACK TEXT_BG_SET(137)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_BLACK TEXT_BG_SET(138)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_BLACK TEXT_BG_SET(139)
#define TEXT_BG_BRIGHT_RED_BRIGHT_BLACK TEXT_BG_SET(140)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_BLACK TEXT_BG_SET(141)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_BLACK TEXT_BG_SET(142)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_BLACK TEXT_BG_SET(143)

#define TEXT_BG_BLACK_BRIGHT_BLUE TEXT_BG_SET(144)
#define TEXT_BG_BLUE_BRIGHT_BLUE TEXT_BG_SET(145)
#define TEXT_BG_GREEN_BRIGHT_BLUE TEXT_BG_SET(146)
#define TEXT_BG_CYAN_BRIGHT_BLUE TEXT_BG_SET(147)
#define TEXT_BG_RED_BRIGHT_BLUE TEXT_BG_SET(148)
#define TEXT_BG_MAGENTA_BRIGHT_BLUE TEXT_BG_SET(149)
#define TEXT_BG_YELLOW_BRIGHT_BLUE TEXT_BG_SET(150)
#define TEXT_BG_WHITE_BRIGHT_BLUE TEXT_BG_SET(151)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_BLUE TEXT_BG_SET(152)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_BLUE TEXT_BG_SET(153)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_BLUE TEXT_BG_SET(154)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_BLUE TEXT_BG_SET(155)
#define TEXT_BG_BRIGHT_RED_BRIGHT_BLUE TEXT_BG_SET(156)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_BLUE TEXT_BG_SET(157)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_BLUE TEXT_BG_SET(158)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_BLUE TEXT_BG_SET(159)

#define TEXT_BG_BLACK_BRIGHT_GREEN TEXT_BG_SET(160)
#define TEXT_BG_BLUE_BRIGHT_GREEN TEXT_BG_SET(161)
#define TEXT_BG_GREEN_BRIGHT_GREEN TEXT_BG_SET(162)
#define TEXT_BG_CYAN_BRIGHT_GREEN TEXT_BG_SET(163)
#define TEXT_BG_RED_BRIGHT_GREEN TEXT_BG_SET(164)
#define TEXT_BG_MAGENTA_BRIGHT_GREEN TEXT_BG_SET(165)
#define TEXT_BG_YELLOW_BRIGHT_GREEN TEXT_BG_SET(166)
#define TEXT_BG_WHITE_BRIGHT_GREEN TEXT_BG_SET(167)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_GREEN TEXT_BG_SET(168)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_GREEN TEXT_BG_SET(169)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_GREEN TEXT_BG_SET(170)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_GREEN TEXT_BG_SET(171)
#define TEXT_BG_BRIGHT_RED_BRIGHT_GREEN TEXT_BG_SET(172)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_GREEN TEXT_BG_SET(173)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_GREEN TEXT_BG_SET(174)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_GREEN TEXT_BG_SET(175)

#define TEXT_BG_BLACK_BRIGHT_CYAN TEXT_BG_SET(176)
#define TEXT_BG_BLUE_BRIGHT_CYAN TEXT_BG_SET(177)
#define TEXT_BG_GREEN_BRIGHT_CYAN TEXT_BG_SET(178)
#define TEXT_BG_CYAN_BRIGHT_CYAN TEXT_BG_SET(179)
#define TEXT_BG_RED_BRIGHT_CYAN TEXT_BG_SET(180)
#define TEXT_BG_MAGENTA_BRIGHT_CYAN TEXT_BG_SET(181)
#define TEXT_BG_YELLOW_BRIGHT_CYAN TEXT_BG_SET(182)
#define TEXT_BG_WHITE_BRIGHT_CYAN TEXT_BG_SET(183)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_CYAN TEXT_BG_SET(184)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_CYAN TEXT_BG_SET(185)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_CYAN TEXT_BG_SET(186)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_CYAN TEXT_BG_SET(187)
#define TEXT_BG_BRIGHT_RED_BRIGHT_CYAN TEXT_BG_SET(188)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_CYAN TEXT_BG_SET(189)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_CYAN TEXT_BG_SET(190)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_CYAN TEXT_BG_SET(191)

#define TEXT_BG_BLACK_BRIGHT_RED TEXT_BG_SET(192)
#define TEXT_BG_BLUE_BRIGHT_RED TEXT_BG_SET(193)
#define TEXT_BG_GREEN_BRIGHT_RED TEXT_BG_SET(194)
#define TEXT_BG_CYAN_BRIGHT_RED TEXT_BG_SET(195)
#define TEXT_BG_RED_BRIGHT_RED TEXT_BG_SET(196)
#define TEXT_BG_MAGENTA_BRIGHT_RED TEXT_BG_SET(197)
#define TEXT_BG_YELLOW_BRIGHT_RED TEXT_BG_SET(198)
#define TEXT_BG_WHITE_BRIGHT_RED TEXT_BG_SET(199)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_RED TEXT_BG_SET(200)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_RED TEXT_BG_SET(201)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_RED TEXT_BG_SET(202)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_RED TEXT_BG_SET(203)
#define TEXT_BG_BRIGHT_RED_BRIGHT_RED TEXT_BG_SET(204)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_RED TEXT_BG_SET(205)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_RED TEXT_BG_SET(206)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_RED TEXT_BG_SET(207)

#define TEXT_BG_BLACK_BRIGHT_MAGENTA TEXT_BG_SET(208)
#define TEXT_BG_BLUE_BRIGHT_MAGENTA TEXT_BG_SET(209)
#define TEXT_BG_GREEN_BRIGHT_MAGENTA TEXT_BG_SET(210)
#define TEXT_BG_CYAN_BRIGHT_MAGENTA TEXT_BG_SET(211)
#define TEXT_BG_RED_BRIGHT_MAGENTA TEXT_BG_SET(212)
#define TEXT_BG_MAGENTA_BRIGHT_MAGENTA TEXT_BG_SET(213)
#define TEXT_BG_YELLOW_BRIGHT_MAGENTA TEXT_BG_SET(214)
#define TEXT_BG_WHITE_BRIGHT_MAGENTA TEXT_BG_SET(215)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_MAGENTA TEXT_BG_SET(216)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_MAGENTA TEXT_BG_SET(217)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_MAGENTA TEXT_BG_SET(218)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_MAGENTA TEXT_BG_SET(219)
#define TEXT_BG_BRIGHT_RED_BRIGHT_MAGENTA TEXT_BG_SET(220)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_MAGENTA TEXT_BG_SET(221)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_MAGENTA TEXT_BG_SET(222)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_MAGENTA TEXT_BG_SET(223)

#define TEXT_BG_BLACK_BRIGHT_YELLOW TEXT_BG_SET(224)
#define TEXT_BG_BLUE_BRIGHT_YELLOW TEXT_BG_SET(225)
#define TEXT_BG_GREEN_BRIGHT_YELLOW TEXT_BG_SET(226)
#define TEXT_BG_CYAN_BRIGHT_YELLOW TEXT_BG_SET(227)
#define TEXT_BG_RED_BRIGHT_YELLOW TEXT_BG_SET(228)
#define TEXT_BG_MAGENTA_BRIGHT_YELLOW TEXT_BG_SET(229)
#define TEXT_BG_YELLOW_BRIGHT_YELLOW TEXT_BG_SET(230)
#define TEXT_BG_WHITE_BRIGHT_YELLOW TEXT_BG_SET(231)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_YELLOW TEXT_BG_SET(232)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_YELLOW TEXT_BG_SET(233)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_YELLOW TEXT_BG_SET(234)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_YELLOW TEXT_BG_SET(235)
#define TEXT_BG_BRIGHT_RED_BRIGHT_YELLOW TEXT_BG_SET(236)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_YELLOW TEXT_BG_SET(237)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_YELLOW TEXT_BG_SET(238)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_YELLOW TEXT_BG_SET(239)

#define TEXT_BG_BLACK_BRIGHT_WHITE TEXT_BG_SET(240)
#define TEXT_BG_BLUE_BRIGHT_WHITE TEXT_BG_SET(241)
#define TEXT_BG_GREEN_BRIGHT_WHITE TEXT_BG_SET(242)
#define TEXT_BG_CYAN_BRIGHT_WHITE TEXT_BG_SET(243)
#define TEXT_BG_RED_BRIGHT_WHITE TEXT_BG_SET(244)
#define TEXT_BG_MAGENTA_BRIGHT_WHITE TEXT_BG_SET(245)
#define TEXT_BG_YELLOW_BRIGHT_WHITE TEXT_BG_SET(246)
#define TEXT_BG_WHITE_BRIGHT_WHITE TEXT_BG_SET(247)
#define TEXT_BG_BRIGHT_BLACK_BRIGHT_WHITE TEXT_BG_SET(248)
#define TEXT_BG_BRIGHT_BLUE_BRIGHT_WHITE TEXT_BG_SET(249)
#define TEXT_BG_BRIGHT_GREEN_BRIGHT_WHITE TEXT_BG_SET(250)
#define TEXT_BG_BRIGHT_CYAN_BRIGHT_WHITE TEXT_BG_SET(251)
#define TEXT_BG_BRIGHT_RED_BRIGHT_WHITE TEXT_BG_SET(252)
#define TEXT_BG_BRIGHT_MAGENTA_BRIGHT_WHITE TEXT_BG_SET(253)
#define TEXT_BG_BRIGHT_YELLOW_BRIGHT_WHITE TEXT_BG_SET(254)
#define TEXT_BG_BRIGHT_WHITE_BRIGHT_WHITE TEXT_BG_SET(255)

#define TEXT_RESET TEXT_BG_WHITE_BLACK

std::string TEXT_RGB( int R = 0, int G = 0, int B = 0 )
{
	return "";
}

std::string BG_RGB( int R = 0, int G = 0, int B = 0 )
{
	return "";
}

#endif